data:extend(
    {
          {
            type = "fluid",
            name = "syrup",
			localised_name = {"fluid-name.syrup"},
            icon = "__baketorio_plus__/graphics/syrup.png",
            icon_size = 32,
            subgroup = "ingredient",
            default_temperature = 25,
            heat_capacity = "0.1kJ",
            base_color = {r = 0.78, g = 0.69, b = 0.24},
            flow_color = {r = 0.78, g = 0.69, b = 0.24},
            max_temperature = 100,
            pressure_to_speed_ratio = 0.1,
            flow_to_energy_ratio = 0.59,
          },
		{
			type = "fluid",
			name = "sugar-water",
			localised_name = {"fluid-name.sugar-water"},
			icon = "__baketorio_plus__/graphics/sugar-water.png",
            icon_size = 32,
			subgroup = "ingredient",
			default_temperature = 15,
			max_temperature = 100,
			heat_capacity = "2kJ",
			base_color = {0, 0.34, 0.6},
			flow_color = {0.7, 0.7, 0.7},
		--	order = "a[fluid]-a[sugar-water]-a[sugar-water]"
		},
		--{
		--	type = "fluid",
		--	name = "syrup",
		--	subgroup = "fluid",
		--	default_temperature = 15,
		--	max_temperature = 5000,
		--	heat_capacity = "0.2kJ",
		--	icon = "__base__/graphics/icons/fluid/steam.png",
		--	base_color = {r = 0.78, g = 0.69, b = 0.24},
		--	flow_color = {r = 0.78, g = 0.69, b = 0.24},
		--	order = "a[fluid]-a[sugar-water]-b[syrup]",
		--	gas_temperature = 15,
		--	auto_barrel = false
		--},
        {
            type = "fluid",
            name = "fertilized-water",
			localised_name = {"fluid-name.fertilized-water"},
            icon = "__baketorio_plus__/graphics/fertilized-water.png",
            icon_size = 32,
            subgroup = "fluid",
            default_temperature = 25,
            heat_capacity = "0.1kJ",
            base_color = {r = 0.1, g = 0.1, b = 0.99},
            flow_color = {r = 0.1, g = 0.1, b = 0.99},
            max_temperature = 100,
            pressure_to_speed_ratio = 0.4,
            flow_to_energy_ratio = 0.59,
        },
		
        {
            type = "fluid",
            name = "chocolate-sauce",
			localised_name = {"fluid-name.chocolate-sauce"},
            icon = "__baketorio_plus__/graphics/chocolate-sauce.png",
            icon_size = 32,
            subgroup = "chocolate",
            default_temperature = 25,
            heat_capacity = "0.1kJ",
            base_color = {r = 0.1, g = 0.1, b = 0.99},
            flow_color = {r = 0.1, g = 0.1, b = 0.99},
            max_temperature = 100,
            pressure_to_speed_ratio = 0.4,
            flow_to_energy_ratio = 0.59,
        },
        {
            type = "fluid",
            name = "white-chocolate-sauce",
			localised_name = {"fluid-name.white-chocolate-sauce"},
            icon = "__baketorio_plus__/graphics/white-chocolate-sauce.png",
            icon_size = 32,
            subgroup = "chocolate",
            default_temperature = 25,
            heat_capacity = "0.1kJ",
            base_color = {r = 0.1, g = 0.1, b = 0.99},
            flow_color = {r = 0.1, g = 0.1, b = 0.99},
            max_temperature = 100,
            pressure_to_speed_ratio = 0.4,
            flow_to_energy_ratio = 0.59,
        },
		
        {
            type = "fluid",
            name = "gelatin",
			localised_name = {"fluid-name.gelatin"},
            icon = "__baketorio_plus__/graphics/gelatin.png",
            icon_size = 32,
            subgroup = "ingredient",
            default_temperature = 25,
            heat_capacity = "0.1kJ",
            base_color = {r = 0.1, g = 0.1, b = 0.99},
            flow_color = {r = 0.1, g = 0.1, b = 0.99},
            max_temperature = 100,
            pressure_to_speed_ratio = 0.4,
            flow_to_energy_ratio = 0.59,
        },
        {
            type = "fluid",
            name = "gravy",
			localised_name = {"fluid-name.gravy"},
            icon = "__baketorio_plus__/graphics/gravy.png",
            icon_size = 32,
            subgroup = "ingredient",
            default_temperature = 25,
            heat_capacity = "0.1kJ",
            base_color = {r = 0.1, g = 0.1, b = 0.99},
            flow_color = {r = 0.1, g = 0.1, b = 0.99},
            max_temperature = 100,
            pressure_to_speed_ratio = 0.4,
            flow_to_energy_ratio = 0.59,
        },
        {
            type = "fluid",
            name = "cobbler-mixture",
			localised_name = {"fluid-name.cobbler-mixture"},
            icon = "__baketorio_plus__/graphics/cobbler-mixture.png",
            icon_size = 32,
            subgroup = "ingredient",
            default_temperature = 25,
            heat_capacity = "0.1kJ",
            base_color = {r = 0.1, g = 0.1, b = 0.99},
            flow_color = {r = 0.1, g = 0.1, b = 0.99},
            max_temperature = 100,
            pressure_to_speed_ratio = 0.4,
            flow_to_energy_ratio = 0.59,
        },
        {
            type = "fluid",
            name = "lemon-juice",
			localised_name = {"fluid-name.lemon-juice"},
            icon = "__baketorio_plus__/graphics/lemon-juice.png",
            icon_size = 32,
            subgroup = "ingredient",
            default_temperature = 25,
            heat_capacity = "0.1kJ",
            base_color = {r = 0.1, g = 0.1, b = 0.99},
            flow_color = {r = 0.1, g = 0.1, b = 0.99},
            max_temperature = 100,
            pressure_to_speed_ratio = 0.4,
            flow_to_energy_ratio = 0.59,
        },
    }
)
